### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by zichangyibeizi** [orex/supercell#13]
Hi,

I followed quick installation instruction for supercell. But i always meet a problem which I show  in attached picture. 

I am sure that I succeeded in installation of Open babel in my computer. making test also shows 100% pass. and then I use the command that:  git clone --recursive https://github.com/orex/supercell.git && cd supercell && \ mkdir build && cd build && cmake ../ && make && sudo make install

I am very confusing with this Error. I work on Ubuntu OS with administrator permission. 

could you help me solve this problem?

I am looking forward to your reply.

thanks,

![screenshot from 2018-09-24 00-11-19](https://user-images.githubusercontent.com/37132170/45938322-87d5d800-bf8e-11e8-98e0-ab85d14f6d5a.png)

**Comment by orex** [comment]
Dear zichangyibeizi,

Thank you for reporting the issue and special thanks for reporting it via Github interface.

The problem is that new version of gcc compiler in Ubuntu 18.04 "more strict" about `static const double` members of the class. I've done a trivial fix to avoid the problem. Please check the latest version of the code.

I know nothing about your project, but I can assume that you would like to do more, than just to try my program, because most of the end users of _supercell_ prefer precompiled binaries. Probably the information below will be useful for you.
1) The latest stable version of openbabel 2.4 is compatible with _supercell_ program. The version will be default in ubuntu 18.10 release.
2) The supercell source code repository consists of the program itself and manual/tutorial source code (LaTeX) which can be automatically compiled to man/html/pdf file. If you don't want it to me compiled, you can skip this.

`make doc_man/html/pdf` - makes man file in the format. The files can be found here.   https://orex.github.io/supercell/#read-more manual subsection.
You should do `make doc_man` if you would like to `man supercell` working.

`make tutorial_pdf` -  makes the tutorial: https://orex.github.io/supercell/doc/supercell_tutorial.pdf I don't think that you need to compile it by yourself unless you would like to change it. So, I would recommend you to go for this. 

... `cmake ../ && make supercell && make doc_man && sudo make install`

3) I would recommend to run some examples from tutorial to verify the compilation/installation of the program.

Kirill.

**Comment by zichangyibeizi** [comment]
Dear Kirill,

thanks for your attention.

I have tired the command that you gave to me. I still met the error about making doc_pdf. the attached is error message.
![screenshot from 2018-09-24 04-05-39](https://user-images.githubusercontent.com/37132170/45944269-24a86d80-bfaf-11e8-94f0-064b8649a922.png)

it seems that it created a executable supercell. but i cannot find it (typically it will be in bin directory but i find one in build/src/sc_cli directory which does not work. error is ).

![screenshot from 2018-09-24 04-08-46](https://user-images.githubusercontent.com/37132170/45944367-8ec11280-bfaf-11e8-82ec-557266239552.png)


I also tired binary version, which is downloaded from https://orex.github.io/supercell/exe/supercell-linux.tar.gz. I run it with executable supercell but I got same error.

I am so sorry to bother you again.

thanks,

Zichang

**Comment by orex** [comment]
1) Please run from folder ...`build/src/sc_cli` command
`./supercell -d -m -i ../../../data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif`
 and show the output.
2) Please attach the file Ca2Al2SiO7.cif used for your run.

**Comment by zichangyibeizi** [comment]
Dear Kirill,

![screenshot from 2018-09-24 04-32-57](https://user-images.githubusercontent.com/37132170/45945526-64715400-bfb3-11e8-8e4e-e3483000bc37.png)
![screenshot from 2018-09-24 04-34-29](https://user-images.githubusercontent.com/37132170/45945538-705d1600-bfb3-11e8-911a-27e6c790e0fa.png)
![screenshot from 2018-09-24 04-35-46](https://user-images.githubusercontent.com/37132170/45945552-75ba6080-bfb3-11e8-8028-6791e801ffe8.png)

I am not sure why there is a lot warning about open babel. So I also run obabel -i ../../../data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif -o Ca2Al2SiO7.xyz        here is an error:

![screenshot from 2018-09-24 04-32-15](https://user-images.githubusercontent.com/37132170/45945555-7b17ab00-bfb3-11e8-9e4d-da72dab4046e.png)

thanks,

Zichang

**Comment by orex** [comment]
1) The first screenshot clearly shows, that openbabel installation is corrupted, but my program can read the file.
2) Second screenshot. The data on the second picture (symmetry operation 1) usually say, that you have a wrong version of openbabel, but in your case it can be corrupted installation. I don't know.
3) 3rd screenshot. File is OK, but I've asked about file in sc_cil folder, which your run first time. That file looks corrupted.
4) 4th screenshot. You run obabel wrong. Please check the obabel help in your last picture carefully and run it again.
5) Please install binary version of supercell properly (as readme said) and run it on data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif file.

**Comment by zichangyibeizi** [comment]
I run example by binary version. Input file cannot be opened

![screenshot from 2018-09-24 05-00-13](https://user-images.githubusercontent.com/37132170/45946521-c1223e00-bfb6-11e8-9027-54b1bfb207f9.png)

**Comment by zichangyibeizi** [comment]
does this binary version rely on openbabel?

**Comment by orex** [comment]
I don't want to be intrusive but,
Please, `cat ~/workplace/software/supercell1/Ca2Al2SiO7.cif` in folder supercell1 as I'm asking and asking and asking ...
Just `cat` and publish don't do anything else.

**Comment by zichangyibeizi** [comment]
Dear Kirill,

Right now, I know that using wget to download Ca2Al2SiO7.cif is TOTALLY wrong way. I just downloaded a wrong input file. after I download a right inout file. result is like:
![screenshot from 2018-09-24 05-17-55](https://user-images.githubusercontent.com/37132170/45947264-35f67780-bfb9-11e8-9957-f6082293e10b.png)

It is a right result.

Thanks very much. thanks for your patient.

Zichang

**Comment by orex** [comment]
The result is right! What about supercell compiled by yourself? Is it produces the same result?

P.S. If you would like to download from github with wget use raw button on the file page. 
![image](https://user-images.githubusercontent.com/3882045/45948563-27cc4980-c001-11e8-8911-ff3f8cb1696e.png)

You will get the link like this https://raw.githubusercontent.com/orex/supercell/master/data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif which you can use with wget.

**Comment by zichangyibeizi** [comment]
I gave up using supercell compiled by myself. Binary version is much easier to use.

I have copied data file from downloaded source file. all the examples work very well.

thanks very much,

Best regards,

Zichang

**Comment by orex** [comment]
Dear Zichang,

Thank you again for the issue. You help me to fix the compilation bug with new gcc compiler. 

The binary version of _supercell_ do not rely neither to openbabel nor for any other special libs and can work on any linux systems (64 bits) without additional libraries needed. Therefore you can safely remove openbabel from system. Please also refer to https://orex.github.io/supercell/ site the latest versions of manual and tutorial. 

Good luck with your project! And feel free to contact me in case of any further problems. 

Sincerely yours,
Kirill.
