### ISSUE TITLE
Comparison to icet code

### ISSUE THREAD

**Issue by blokhin** [orex/supercell#29]
Dear Kirill @orex,

How does the supercell code compare to the [icet](https://gitlab.com/materials-modeling/icet) code? Could they replace each other?

Many thanks for your time!

**Comment by orex** [comment]
Dear Evgeny,

Thank you much for the message. I've not notice the package before. The package looks very interesting and reliable. It is really difficult to explicit compare the solutions, because they are different. Supercell is a software for a structures enumeration. Icet is a complex solution for cluster expansion theory and one part of the approach is a structure enumeration. As I understand, icet use their own pure python solution for structure enumeration, which, from my point of view, is a very low performance. From another side, nobody restricts my program to be a enumeration solution in ASE (https://gitlab.com/ase/ase/-/merge_requests/896).
Enumerating structures is a base for many methods (not only cluster expansion), like NSGA family (https://doi.org/10.1039/C8CP05284K), MDTS (https://doi.org/10.1080/14686996.2017.1344083) and "electrostatic sorting" of result structures implement in my program.
From my point of view, cluster expansion method is the best for random or nearly random structures, where all structures can exists with slightly different energy. "Pure supercell" and electrostatic sorting are doing well with correlated disorder structures. For such compounds some of the enumerated structures simply cannot exists (geometry optimization simple destroy the lattice).
Another side difference is that my program is a CLI program, but icet is a library for python. You need to make a program to get a result from icet.
Feel free to ask any other details if you need.
