### ISSUE TITLE
Coulomb energy calculation

### ISSUE THREAD

**Issue by Traecp** [orex/supercell#4]
Dear developers,
I have tried to run supercell with Coulomb energy calculation option (-q) for a perovskite material KTa_{1-x}Nb_xO_3. As a result I obtained all calculated supercells with the same energy.
Here is the command I run: 
> supercell -i KTN23_6122.cif -m -q -s 2x2x2

The cif file is attached here. I have changed the extension to TXT because this forum does not allow .cif file. Please change it to .cif when you run it.

[KTN23_6122.txt](https://github.com/orex/supercell/files/313487/KTN23_6122.txt)

Could you please have a look why the Coulomb energy are the same? I tried with a larger supercell (3x3x3) and still have the same energy every where.
Thank you very much.
Tra

**Comment by orex** [comment]
Dear Tra,

The supercell program gives proper result. You have one disordered site (Ta1/Nb1) and both atoms have the same charge +5. Therefore, the supercell code gives the same energy for all structures. In order to obtain different Coulomb energy you should supply different charges to the program input. You can take this charges from DFT calculations or from literature, if it is exists there. If you decide to make your own DFT, it will be good to check the correlation between Coulomb energy and total DFT energy. We wrote a paper about it, where we discuss the problem in detail, but it is not yet published. Hope it will be published within a few month.

Best,
Kirill.
