### ISSUE TITLE
How to start with supercell

### ISSUE THREAD

**Issue by Fmw-sr** [orex/supercell#49]
Dear Supercell developers,
 
I would like to ask a simple but confusing question for me. The problem is, when I try to start the supercell program like the tutorial and find:

bash :  supercell : command not find ..

I think it's because I didn't add it to the environment. But I don't know what I need to add to the environment. 

Thank you very much, and your answer is very important to me.

Sorry, maybe i has download the source code. I well try the compiled binaries.

**Comment by Fmw-sr** [comment]
Thanks a lot, I have successfully started the program with the ./supercell command. I tried some examples and found another problem, when I try to calculate the coulomb energy, which is using the 

mkdir cell113_out/
supercell -i Fe2O3-P4332.cif -s 1x1x3 -m -q -v 2 -o cell113_out/cell113

command in supercell/data/examples/gamma-Fe2O3/. And i find there is no output file named cell113_coulomb_energy.txt in cell113_out/.

**Comment by Ccandcc** [comment]
That's a very good program, Thanks a lot, but whether there is the option of multi-core parallel computing when I use it, because in the process of using, only one core of cpu can be used. 
that will appear when I use this program in Red Hat, such a large Primitive cell which contains almost 128 atoms，the occupation of cpu is just 3%
WARN: The number of combinations to check is high 281474976710656
WARN: Structure is too big and/or problems with charges values.281474976710656

**Comment by orex** [comment]
Hello!
Unfortunately I did not get your message fully. Last version of `supercell` is parallel by default. You do not need to specify any options. The thing, which confusing me more is that the warning you wrote means that `supercell` algorithm did not stated. This number is really too big to do something. Supercell program can run for ~ half year with such huge number of combinations, therefore it is interrupted.

**Comment by orex** [comment]
Closed due to inactivity.
