### ISSUE TITLE
Large enumeration and MonteCarlo scheme

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [orex/supercell#63]
Hallo,

I am playing with LiPSCl crystal and in literature people said it sais anion disorder. I construct the cif file and run the program here is the output for just 1x1x1 supercell size.

Command line: `./supercell -i Li6PS5Cl_structure_from_2012_paper.cif -s 1x1x1 -m -n r500 -v 2 -o ./2012/Li6PS5Cl_structure_from_2012_paper_1x1x1`
```
Random SEED: 1166064087
CIF file info:
  INFO: Using symmetries from space group.

Initial system:
  Chemical Formula: Cl4 Li21.12 P4 S52

Supercell system (1x1x1):
  Size a=10.2795, b=10.2795, c=10.2795

Current charge balance option is "try"
Total charge oxidation state (cif):  0
Total charge cell:   0
Charge balancing:   yes
----------------------------------------------------------------
| Atom Label    |       charge          | mult  | occup x mult
|               | Ox. state     | Used  | (cif) |
----------------------------------------------------------------
|  Cl1          |  0            |  0    |  4    |  1.48
|  Cl2          |  0            |  0    |  4    |  2.52
|  Li1          |  0            |  0    |  48   |  21.12
|  P            |  0            |  0    |  4    |  4
|  S1           |  0            |  0    |  4    |  2.52
|  S2           |  0            |  0    |  4    |  1.48
|  S3           |  0            |  0    |  48   |  48
----------------------------------------------------------------

Chemical formula of the supercell: Cl4 Li21 P4 S52
Total charge of supercell: 0

----------------------------------------------------
 Identification of groups of crystallographic sites
----------------------------------------------------

 Group 1 (4 atomic positions in supercell):
  * Site #1: Cl1 (occ. 0.37) -> distributed over 1 positions out of 4 (actual occ.: 0.250).
  * Site #2: S1 (occ. 0.63) -> distributed over 3 positions out of 4 (actual occ.: 0.750).
  Number of combinations for the group is 4

 Group 2 (4 atomic positions in supercell):
  * Site #1: Cl2 (occ. 0.63) -> distributed over 3 positions out of 4 (actual occ.: 0.750).
  * Site #2: S2 (occ. 0.37) -> distributed over 1 positions out of 4 (actual occ.: 0.250).
  Number of combinations for the group is 4

 Group 3 (48 atomic positions in supercell):
  * Site #1: Li1 (occ. 0.44) -> distributed over 21 positions out of 48 (actual occ.: 0.438).
  Number of combinations for the group is 22314239266528

 Group 4 (4 atomic positions in supercell):
  * Site #1: P (occ. 1) -> FIXED with occupancy 1.000.

 Group 5 (48 atomic positions in supercell):
  * Site #1: S3 (occ. 1) -> FIXED with occupancy 1.000.

Minimal distance between atoms of two distinct groups: 1.58443 A.

-------------------------------------------------
The total number of combinations is 357027828264448(~3.6e+14)
```

Instead of enumeration is there a plan in future to use MC to get structre based on some criterion. Is there a way to get crude approximation rather than doing enumeration. 

Thanks,
Asif

**Comment by orex** [comment]
Hello, Asif!

Thanks for the interest to my program.
1) It is possible to enumerate even such huge amount of structures. Take a fast multicore node in HPC. It can take a week or so.
2) There is no plan to use MC to get structure based on some criterion. Some private (not published) research I did showed that MC approach is quite difficult to setup to achieve e.g. structure with lowest electrostatic energy. Current approach gives guaranty, that the structures you get are fulfill the criteria for 100%.
3) if you would like to get a random structure, please check the paper below. It describe the way to get this.
https://arxiv.org/abs/1606.08062
4) In your case, where you get several disordered sites, the enumeration can be parallelized even more, if you resolve  the disorder step by step. Please check section "Application of supercell program to Rb-PST-1 zeolite" in the tutorial https://orex.github.io/supercell/docs/tutorial/

Best,
Kirill.

P.S. Don't forget to setup charges, if you would like to perform electrostatic minimization.

**Comment by Asif-Iqbal-Bhatti** [comment]
Okay, thank you. I will look into that example and the paper. 

THe charges are quite tricky sometimes when we construct a unicell format the paper the author does not specify which charge were used. As an approximation when I use the charges from Materials project that the supercell program gives error stating the the total charge of the supercell is not zero and it exits.

**Comment by Gitdowski** [comment]
Hi Asif,
I have been working with the related Li6PS5Br, which has almost the same crystal structure, so I'm sharing my perspective on your case. 

As you can see, the huge number of combinations is mostly due to the Li sublattice, even though you are only working with conventional unit cell of the system (where you can control your Cl/S disorder only in 25% steps). This is because the Li sublattice has quite a number of sites, many of them are packed very close together and will never be occupied simultaneously (e.g., the combination of 3 sites often termed T5-T5a-T5 is almost always only occupied by 1 Li at a time). If you extend your system to a supercell the number of combinations will skyrocket even more.

Moreover, the system you are investigating in is a superionic conductor with a very high Li conductivity. This means the Li is highly mobile and never resides on its site for a long time and I regard this situation more as a dynamical steady-state. Therefore, I don't see much value in getting the most favorable structure in terms of Li-distribution, because I expect that there are many degenerate structures with almost the same energy. 

What's the way out? 
a) If you want to keep on using supercell for occupying the Li sublattice, you could use more detailed crystallographic information. Knowing the system a bit, I believe you are already doing so because you only treat the Li1 site which should contain 21 Li ions according to your output. Therefore, the following might not be relevant to you. Instead of letting supercell distribute all Li ions over all sites, you could work with the different Li sites that have been experimentally observed and for which partial occupancies should be available. I don't know how many Li sites people have identified for Li6PS5Cl, but I guess there should also be at least 2 or 3 different sites on the Li sublattice. Splitting the 48 sights into those 2 or 3 groups will result in a considerable reduction of you combinations. If this is still too much to handle, you can think about occupying those sites one by one, instead of letting supercell handle all at once. 

b) If you want to use larger supercells, you could also think about not touching your Li sites at all and keep them with partial occupancies (acting like a homogeneous background). For such structures you can occupy the Cl/S sublattice first. Next, you identify one site that could host all Li ions and simply place them there. Of course, such an easy and artificial distribution does not correspond to reality. But running some (ab-initio) molecular dynamics (AI)MD should be enough to let the fast Li re-distribute and find some reasonable configurations. After the system has equilibrated, you could extract structures every X-th step and perform a structural relaxation on those. I did it similarly in the past and simplified the T5-T5a-T5 situation by only occupying all T5a sites. Just be warned: Such an artificial distribution might lead to different lattice constants if you also optimize the volume for such an initial structure. In my case, I observed that they very artificially high, but that I only realized after I had already run AIMD simulations to analyze the Li diffusion.

Maybe these references will be helpful to you: 
https://doi.org/10.1021/acs.chemmater.9b03852
https.//doi.org/10.1002/aenm.202003369
https://doi.org/10.1098/rsta.2019.0458

A last comment to the charges: Because you are only working with the Li1 sites that I mentioned above, your system is Li deficient. There should be Li2 and/or Li3 sites. Those information must be added in the cif file if you want to use the electrostatic enumeration with reasonable charges. Your current composition is reflected in the line
`Chemical formula of the supercell: Cl4 Li21 P4 S52`
The Li content should be 24 to have a neutral structure.


Sorry, if I spouted too much, but I hope it will be helpful :-)
Cheers,
Marcel
