### ISSUE TITLE
Coulomb Energy Calculation Problem: New Structures Obtained from Substitution Doping

### ISSUE THREAD

**Issue by BigBMonster** [orex/supercell#67]
Hello, Author,

The supercell generation structure is very useful. I used Cu to substitute Co in layered transition metal oxides (LiCoO₂) and obtained many new structures.

The atomic composition of LiCoO₂ after expanding the 2x2x1 unit cell is Li₁₂Co₁₂O₂₄, and after doping with Cu, the atomic composition is Li₁₂Co₉Cu₃O₂₄.

Given the oxidation states: Li: +1, O: -2, Co: +3 or +4, Cu: +1 or +2, I want to calculate the Coulomb energy of the new structure to select the one with the lowest energy. However, I find that I cannot achieve charge balance. How should I calculate the Coulomb energy of the new structure?

**Comment by Gitdowski** [comment]
I see supercell "only" as a mathematical model that allows you to iterate over the different arrangements of atoms and uses the specified oxidation states to calculate the electrostatic energy. It does not know/care about the physical reasons behind these oxidation states. It is your task to provide eligible oxidation states to supercell such that charge balance can be achieved. 

If you keep 100% of your Li sites occupied, then adding one Cu will introduce changes in the oxidation state of one or more Co ions. Considering the very first Cu ion that you add to the structure, I see two possibilities to keep charge neutrality: 
a) The Cu is in a 2+ state, resulting in one Co to turn from 3+ to 4+. 
b) The Cu is in a 1+ state, requiring two Co to become 4+. (Technically also one Co could be specified as +5, but we know that this would never happen in reality)
I am not familiar with the order of the energy levels to guess which one is more likely, but a DFT calculation should tell you which one is more favorable (potentially depending on the initialization for the magnetic moments).

If the Co 3+ to 4+ and the Cu 1+ to 2+ transitions are very close in energy, things can become quite complicated as soon as you add more Cu (and even worse if you start taking out Li ions), because then the distribution of the atoms matters a lot and you cannot a priori tell the local oxidation state of your transition metal atoms. 
I could see three ways to treat your system. You need to decide which one is more appropriate/doable for your case:
1) Neglect one oxidation state. E.g. if you know that Cu preferably stays in a 2+ plus state all the time, define only this state. Then you can define two types for Co, one with +3 and one other with +4 states. You can do so by giving two distinct Co types with different names. You do this for a specific composition and take care that the corresponding occupancy factors yield a charge-neutral system.
2) Simplify the situation by using an averaged oxidation state for one of the types. This is a kind of mean-field approach. E.g. use a fixed Cu oxidation state, calculate what average oxidation state for Co would be necessary to make it charge neutral.
3) Use the full palette of the available oxidation states. For this you need to define a different atomic type for every combination of species and oxidation state. This would result in 6 types for your example: Li Co3 Co4 Cu1 Cu2 O. All the Co and Co live on the same sublattice, but to make it charge neutral you again need to provide your speculated occupancy factors for every composition you use.

Hope this helps!

**Comment by BigBMonster** [comment]
Thank you for your answer. I realized that I made a mistake in my description of the valences, so here’s the correction: Li: +1, O: -2, Co: +3, Cu: +1 or +2.

We can see that before doping, Li12Co12O24：12×1 + 12×3 + 24×(-2) = 0. After doping, Li12Co9Cu3O24：12×1 + 9×3 + 3×[1 or 2 (the oxidation state of Cu)] + 24*(-2) ≠ 0. The lack of charge neutrality means I cannot calculate the Coulomb energy.

You mentioned that I can specify oxidation states that do not exist in reality; could I set Cu to +3 to maintain charge balance, even though in reality, the oxidation states of Cu are only +1 or +2?

**Comment by BigBMonster** [comment]
> Thank you for your answer. I realized that I made a mistake in my description of the valences, so here’s the correction: Li: +1, O: -2, Co: +3, Cu: +1 or +2.
> 
> We can see that before doping, Li12Co12O24：12×1 + 12×3 + 24×(-2) = 0. After doping, Li12Co9Cu3O24：12×1 + 9×3 + 3×[1 or 2 (the oxidation state of Cu)] + 24*(-2) ≠ 0. The lack of charge neutrality means I cannot calculate the Coulomb energy.
> 
> You mentioned that I can specify oxidation states that do not exist in reality; could I set Cu to +3 to maintain charge balance, even though in reality, the oxidation states of Cu are only +1 or +2?

Thank you for your answer. I realized that I made a mistake in my description of the valences, so here’s the correction: Li: +1, O: -2, Co: +3, Cu: +1 or +2.
 We can see that before doping, Li12Co12O24：12×1 + 12×3 + 24×(-2) = 0. After doping, Li12Co9Cu3O24：12×1 + 9×3 + 3×[1 or 2 (the oxidation state of Cu)] + 24*(-2) ≠ 0. The lack of charge neutrality means I cannot calculate the Coulomb energy.
 You mentioned that I can specify oxidation states that do not exist in reality; could I set Cu to +3 to maintain charge balance, even though in reality, the oxidation states of Cu are only +1 or +2?

**Comment by orex** [comment]
If you change the Cu charge to +3 it means the same substitution from electrostatic point of view. So, you will have a set of structures with the same Coulomb energy. In general in such systems, like oxides, substitution in one site change the composition in general. Most probably changing Co->Cu will create vacancies on oxygen site.

**Comment by BigBMonster** [comment]
> If you change the Cu charge to +3 it means the same substitution from electrostatic point of view. So, you will have a set of structures with the same Coulomb energy. In general in such systems, like oxides, substitution in one site change the composition in general. Most probably changing Co->Cu will create vacancies on oxygen site.

Thank you for your response. I have another question:

I generated many structures using supercell, but I didn't calculate the Coulomb energy at that time. Now I want to calculate the Coulomb energy for each structure individually, so I used the following command line: 

./supercell -i "cell_i0000_w54.cif" -p "Na*:c=1" -p "O*:c=-2" -p "Fe*:c=3" -p "Mn*:c=4" -p "Ni*:c=2" -p "Ag*:c=1" -c yes -q -n l100 -o cell_out/cell > cell_out/log.out 

However, I received the following error:

Create atoms population error: 
Change supercell size
Switch off charge balancing
Check manual population settings

What is wrong?
This is one of the structure's CIF files.
[cell_i0000_w54.txt](https://github.com/user-attachments/files/17554535/cell_i0000_w54.txt)

**Comment by Gitdowski** [comment]
I highly recommend that you read the documentation and the tutorials again. Count the atoms in your provided structure, multiply with your specified charges, sum it all up and you will see you do not get a charge of zero.

It is also not clear what you want to achieve here, because you do not have specified "overlapping" sites. All your sites are only specified once with the given atom type situated there and with a Site Occupancy of 1.00. Therefore, supercell has nothing to do and can only run into the charge balancing error.

**Comment by BigBMonster** [comment]
Sorry, I didn’t correctly describe my problem earlier, so now I will describe my calculation process in detail:  

This is my CIF file:
[LiCoO2test.txt](https://github.com/user-attachments/files/17557076/LiCoO2test.txt)

step1:
./supercell -i LiCoO2test.cif -s 3x3x1 -p "Co*:p=24" -p "Cu*:p=3" -m -v 2 -o cell_out1/cell 

I used the above command line to generate structures. Using the “-p” option, I specified that in the mixed Co and Cu site, there are 24 Co atoms and 3 Cu atoms. After running the command, it successfully generated a total of 20 structures. In step 1, I did not calculate the Coulomb energy, so in step 2, I attempted to calculate the Coulomb energy.

step2:
./supercell -i LiCoO2test.cif -s 3x3x1 -p "Co*:p=24" -p "Cu*:p=3" -p "Li*:c=1" -p "O*:c=-2" -p "Co*:c=3" -p "Cu*:c=2" -c yes -q -n l100 -m -v 2 -o cell_out2/cell 

Then, I used the above command line to try to calculate the Coulomb energy. Here, I used the “-p” option to specify: Li: +1, O: -2, Co: +3, Cu: +2, but the command failed. This is the log file:
[logstep2.txt](https://github.com/user-attachments/files/17557106/logstep2.txt)

and an error:
  Create atoms population error:
  Change supercell size
  Switch off charge balancing
  Check manual population settings
![error](https://github.com/user-attachments/assets/203ffb38-8746-4083-8b82-d01da08f6345)

It seems I understand why it failed: 27 × 1 + 24 × 3 + 3 × 2 + 54 × (-2) ≠ 0.

My questions are:

（1）It seems I cannot achieve charge neutrality in the second step because Cu is +2, and Co is +3. When Cu replaces Co in the structure, the charges are no longer balanced.
（2）When using the “-c yes” option, it is supposed to attempt to remove certain atoms to maintain charge balance. However, in step2, the “-c yes” option doesn’t seem to work.

My goal: Select the structure with the lowest Coulomb energy(but I am unable to correctly calculate the Coulomb energy)

**Comment by BigBMonster** [comment]
> 2\. n

Thank you for your suggestions. I carefully reviewed the tutorial and successfully calculated the Coulomb energy, but I encountered a new issue:

This is my structure:
[LiCoO211.txt](https://github.com/user-attachments/files/17607301/LiCoO211.txt)

I used the second method you mentioned, which involves averaging the oxidation states to calculate the Coulomb energy.

I calculated the Coulomb energy using different oxidation states:

First attempt: Cu: +1, Fe: 3.666666
Second attempt: Cu: +2, Fe: 3.333333

This is the command I used for the first run:
./supercell -i LiCoO211.cif -s 2x2x1 -p "Ni*:p=4" -p "Fe*:p=3" -p "Mn*:p=4" -p "Cu*:p=1" -p "Ni*:c=2" -p "Fe*:c=3.66666666" -p "Mn*:c=4" -p "Cu*:c=1" -p "Li*:c=1" -p "O*:c=-2" -q -c yes -m -n l100 -o cell_out6/cell > cell_out6/log.out

Here is the Coulomb energy calculated:
[energy1.txt](https://github.com/user-attachments/files/17607306/energy1.txt)

This is the command used for the second run:
./supercell -i LiCoO211.cif -s 2x2x1 -p "Ni*:p=4" -p "Fe*:p=3" -p "Mn*:p=4" -p "Cu*:p=1" -p "Ni*:c=2" -p "Fe*:c=3.33333333" -p "Mn*:c=4" -p "Cu*:c=2" -p "Li*:c=1" -p "O*:c=-2" -q -c yes -m -n l100 -o cell_out7/cell > cell_out7/log.out

Here is the Coulomb energy calculated:
[energy2.txt](https://github.com/user-attachments/files/17607307/energy2.txt)

My question is:

(1) I noticed that the ranking of the Coulomb energies changes depending on the oxidation states used. I’d like to understand where the issue might lie.

**Comment by BigBMonster** [comment]
> I highly recommend that you read the documentation and the tutorials again. Count the atoms in your provided structure, multiply with your specified charges, sum it all up and you will see you do not get a charge of zero.
> 
> It is also not clear what you want to achieve here, because you do not have specified "overlapping" sites. All your sites are only specified once with the given atom type situated there and with a Site Occupancy of 1.00. Therefore, supercell has nothing to do and can only run into the charge balancing error.

Thank you for your suggestions. I carefully reviewed the tutorial and successfully calculated the Coulomb energy, but I encountered a new issue:

This is my structure:
[LiCoO211.txt](https://github.com/user-attachments/files/17607301/LiCoO211.txt)

I used the second method you mentioned, which involves averaging the oxidation states to calculate the Coulomb energy.

I calculated the Coulomb energy using different oxidation states:

First attempt: Cu: +1, Fe: 3.666666
Second attempt: Cu: +2, Fe: 3.333333

This is the command I used for the first run:
./supercell -i LiCoO211.cif -s 2x2x1 -p "Ni*:p=4" -p "Fe*:p=3" -p "Mn*:p=4" -p "Cu*:p=1" -p "Ni*:c=2" -p "Fe*:c=3.66666666" -p "Mn*:c=4" -p "Cu*:c=1" -p "Li*:c=1" -p "O*:c=-2" -q -c yes -m -n l100 -o cell_out6/cell > cell_out6/log.out

Here is the Coulomb energy calculated:
[energy1.txt](https://github.com/user-attachments/files/17607306/energy1.txt)

This is the command used for the second run:
./supercell -i LiCoO211.cif -s 2x2x1 -p "Ni*:p=4" -p "Fe*:p=3" -p "Mn*:p=4" -p "Cu*:p=1" -p "Ni*:c=2" -p "Fe*:c=3.33333333" -p "Mn*:c=4" -p "Cu*:c=2" -p "Li*:c=1" -p "O*:c=-2" -q -c yes -m -n l100 -o cell_out7/cell > cell_out7/log.out

Here is the Coulomb energy calculated:
[energy2.txt](https://github.com/user-attachments/files/17607307/energy2.txt)

My question is:

(1) I noticed that the ranking of the Coulomb energies changes depending on the oxidation states used. I’d like to understand where the issue might lie.
